import Head from "next/head";
import "../styles/Home.module.css";
import { addTodo } from "../src/redux/actions";
import styles from "../styles/Home.module.css";
import useReduxDispatch from "../src/redux/hook/useReduxDispatch";
import TodoListContainer from "../src/components/containers/TodoListContainer";
import TodoFormContainer from "../src/components/containers/TodoFormContainer";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TodoListContainer />
        <TodoFormContainer />
      </main>
    </div>
  );
}
