import Head from "next/head";
import "../styles/Home.module.css";
import { addTodo } from "../src/redux/actions";
import styles from "../styles/Home.module.css";
import useReduxDispatch from "../src/redux/hook/useReduxDispatch";
import TodoList from "../src/components/todolist";
import TodoForm from "../src/components/todolist/TodoForm";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TodoList />
        <TodoForm />
      </main>
    </div>
  );
}
